server:
    port: 80
# Cors Global -> Necessário criar o arquivo de configuração com anotation @Configuration e criar o método
cors:
    originPatterns: http://localhost,http://localhost:80,http://localhost:8080,http://localhost:5173,https://www.erudio.com.br
file:
    upload-dir: ./upload-dir
security:
    jwt:
        token:
            secret-key: 53cr37 # a secret para gerar o token
            expire-length: 3600000 # tempo em ms
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/rest_with_spring_boot_udemy?useTimezone=true&serverTimezone=UTC
        username: root
        password: senha123
    jpa:
        hibernate:
            ddl-auto: none # Isso significa que o hibernate só vai ler gravar informações, não modificando a estrutura do banco
            # o valor default para ddl-auto seria update
        show-sql: false
    servlet: # usado para trabalhar com arquivos
        multipart:
            enabled: true # habilita o multipart na aplicação (arquivos enviados em várias partes)
            file-size-threshold: 2KB # Valor que irá ocupar em memória antes de gravar em disco
            max-file-size: 1MB # Estabelece o tamanho máximo de um arquivo
            max-request-size: 2MB


# Documentação do Swagger -> Somente para o caminho que possuir a String:
# Tudo que começar com /api/qualquer-coisa/v1/qualquer-caminho
springdoc:
    paths-to-match:
        - /auth/**
        - /api/**/v1/**
    swagger-ui:
        use-root-path: true
