spring:
    datasource:
        dbcp2:
            driver-class-name: com.mysql.cj.jdbc.Driver
            url: jdbc:mysql://192.168.1.102:3306/rest_with_spring_boot_udemy?useTimezone=true&serverTimezone=UTC
            username: root
            password: senha123
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
            show-sql: false
